### ISSUE TITLE
Do not install on Ubuntu 17.04

### ISSUE THREAD

**Issue by joseedil** [forsyde/forsyde-tikz#10] opened 2017-08-16 15:59 UTC
My workarounds so far:

1) add ``export TEXMFLOCAL=/usr/share/texmf`` to the ~/.bashrc file.

2) install the package.

3) refresh tex database with ``sudo texhash``.

Still not sure if the thing is going to the right place...

**Comment by ugeorge** [comment] 2017-08-16 20:41
The install script gets `TEXMFLOCAL` using `kpsewhich` (see [this line](https://github.com/forsyde/forsyde-latex/blob/master/install.sh#L5)). The place _should_ be all right unless Ubuntu 17 uses other variable names for TexLive, or it might be some more fundamental problem there. I am a rookie myself, and was guided by a [StackOverflow thread](https://github.com/forsyde/forsyde-latex/blob/master/install.sh#L5).

**Comment by joseedil** [comment] 2018-03-05 22:30
This is still happening. This time tested on Debian Stretch.

Same workaround works.

**Comment by joseedil** [comment] 2018-03-05 22:32
And by the way, the master branch is broken. Only dev-atom branch is "compiling"

**Comment by ugeorge** [comment] 2018-03-06 07:12
We tested on Ubuntu 16.04, 17.04 and OS X machines and experienced nothing wrong. Which LaTeX compiler suite are you using? When you say "broken" what are you referring to, the installation or the compilation of the reference manual? 

Please recreate the scenario: the commands and the printed error message. Also, try installing both with and without sudo, and tell me which installation fails.

**Comment by joseedil** [comment] 2018-03-06 12:40
Broken means it won't compile the Atom papers.

**Comment by ugeorge** [comment] 2018-03-06 21:20
Please check previous commit in the `issue-10` branch. Let me know if the following commands succeed, and which one fails:

    make install
    sudo make install      # if possible
    make doc

**Comment by joseedil** [comment] 2018-03-14 21:24
Ok, a detailed setup.

1) Clean Debian 9 install.
2) `apt-get install texlive texlive-extra-utils texlive-science.`

3) Environment:
```
$> echo $TEXMFHOME 
$>
```
```

$> echo $TEXMFLOCAL
$> 
```

```
$> tlmgr conf
(running on Debian, switching to user mode!)
=========================== version information ==========================
tlmgr revision 41476 (2016-06-18 02:45:25 +0200)
tlmgr using installation: /usr/share/texlive
TeX Live (http://tug.org/texlive) version 2016

==================== executables found by searching PATH =================
PATH: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
kpsewhich: /usr/bin/kpsewhich
updmap: /usr/bin/updmap
fmtutil: /usr/bin/fmtutil
tlmgr: /usr/bin/tlmgr
tex: /usr/bin/tex
pdftex: /usr/bin/pdftex
mktexpk: /usr/bin/mktexpk
dvips: /usr/bin/dvips
dvipdfmx: /usr/bin/dvipdfmx
=========================== active config files ==========================
texmf.cnf: /etc/texmf/web2c/texmf.cnf
texmf.cnf: /usr/share/texmf/web2c/texmf.cnf
texmf.cnf: /usr/share/texlive/texmf-dist/web2c/texmf.cnf
updmap.cfg: /usr/share/texmf/web2c/updmap.cfg
updmap.cfg: /usr/share/texlive/texmf-dist/web2c/updmap.cfg
fmtutil.cnf: /usr/share/texmf/web2c/fmtutil.cnf
config.ps: /usr/share/texlive/texmf-dist/dvips/config/config.ps
mktex.cnf: /etc/texmf/web2c/mktex.cnf
pdftexconfig.tex: /var/lib/texmf/tex/generic/config/pdftexconfig.tex
============================= font map files =============================
psfonts.map: /var/lib/texmf/fonts/map/dvips/updmap/psfonts.map
pdftex.map: /var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map
ps2pk.map: /var/lib/texmf/fonts/map/dvips/updmap/ps2pk.map
kanjix.map: /var/lib/texmf/fonts/map/dvipdfmx/updmap/kanjix.map
=========================== kpathsea variables ===========================
TEXMFMAIN=/usr/share/texlive/texmf-dist
TEXMFDIST=/usr/share/texlive/texmf-dist
TEXMFLOCAL=/usr/local/share/texmf
TEXMFSYSVAR=/var/lib/texmf
TEXMFSYSCONFIG=/etc/texmf
TEXMFVAR=/home/edil/.texlive2016/texmf-var
TEXMFCONFIG=/home/edil/.texlive2016/texmf-config
TEXMFHOME=/home/edil/texmf
VARTEXFONTS=/tmp/texfonts
TEXMF={/home/edil/.texlive2016/texmf-config,/home/edil/.texlive2016/texmf-var,/home/edil/texmf,/etc/texmf,!!/var/lib/texmf,!!/usr/local/share/texmf,!!/usr/share/texmf,!!/usr/share/texlive/texmf-dist}
SYSTEXMF=/var/lib/texmf:/usr/local/share/texmf:/usr/share/texmf:/usr/share/texlive/texmf-dist
TEXMFDBS={!!/var/lib/texmf,!!/usr/local/share/texmf,!!/usr/share/texmf,!!/usr/share/texlive/texmf-dist}
WEB2C={/home/edil/.texlive2016/texmf-config,/home/edil/.texlive2016/texmf-var,/home/edil/texmf,/etc/texmf,!!/var/lib/texmf,!!/usr/local/share/texmf,!!/usr/share/texmf,!!/usr/share/texlive/texmf-dist}/web2c
TEXPSHEADERS=.:{/home/edil/.texlive2016/texmf-config,/home/edil/.texlive2016/texmf-var,/home/edil/texmf,/etc/texmf,!!/var/lib/texmf,!!/usr/local/share/texmf,!!/usr/share/texmf,!!/usr/share/texlive/texmf-dist}/{dvips,fonts/{enc,type1,type42,type3}}//
TEXCONFIG={/home/edil/.texlive2016/texmf-config,/home/edil/.texlive2016/texmf-var,/home/edil/texmf,/etc/texmf,!!/var/lib/texmf,!!/usr/local/share/texmf,!!/usr/share/texmf,!!/usr/share/texlive/texmf-dist}/dvips//
ENCFONTS=.:{/home/edil/.texlive2016/texmf-config,/home/edil/.texlive2016/texmf-var,/home/edil/texmf,/etc/texmf,!!/var/lib/texmf,!!/usr/local/share/texmf,!!/usr/share/texmf,!!/usr/share/texlive/texmf-dist}/fonts/enc//
TEXFONTMAPS=.:{/home/edil/.texlive2016/texmf-config,/home/edil/.texlive2016/texmf-var,/home/edil/texmf,/etc/texmf,!!/var/lib/texmf,!!/usr/local/share/texmf,!!/usr/share/texmf,!!/usr/share/texlive/texmf-dist}/fonts/map/{kpsewhich,pdftex,dvips,}//
==== kpathsea variables from environment only (ok if no output here) ====
```

**Comment by joseedil** [comment] 2018-03-14 21:30
The Atom DATE 2018 paper will be my golden model.

Install from ForSyDe-LaTeX master branch:

1) User:
```
$> make install
* installing forsydeatom.mf
* installing forsydeatom10.mf
* installing forsydeatom8.mf
* installing forsydeatom14.mf
* generating fontmap for forsydeatom8.tfm
This is METAFONT, Version 2.7182818 (TeX Live 2016/Debian) (preloaded base=mf)

(fonts/forsydeatom8.mf
(/home/edil/texmf/fonts/source/public/typeface/forsydeatom.mf [16] [17]
[18] [19] [20] [32] [33] [34] [35] [36] [37] [48] [49] [50] [51] [52] [53] ) )
Font metrics written on forsydeatom8.tfm.
Output written on forsydeatom8.600gf (17 characters, 5824 bytes).
Transcript written on forsydeatom8.log.
* generating fontmap for forsydeatom10.tfm
This is METAFONT, Version 2.7182818 (TeX Live 2016/Debian) (preloaded base=mf)

(fonts/forsydeatom10.mf
(/home/edil/texmf/fonts/source/public/typeface/forsydeatom.mf [16] [17]
[18] [19] [20] [32] [33] [34] [35] [36] [37] [48] [49] [50] [51] [52] [53] ) )
Font metrics written on forsydeatom10.tfm.
Output written on forsydeatom10.600gf (17 characters, 6592 bytes).
Transcript written on forsydeatom10.log.
* generating fontmap for forsydeatom14.tfm
This is METAFONT, Version 2.7182818 (TeX Live 2016/Debian) (preloaded base=mf)

(fonts/forsydeatom14.mf
(/home/edil/texmf/fonts/source/public/typeface/forsydeatom.mf [16] [17]
[18] [19] [20] [32] [33] [34] [35] [36] [37] [48] [49] [50] [51] [52] [53] ) )
Font metrics written on forsydeatom14.tfm.
Output written on forsydeatom14.600gf (17 characters, 8412 bytes).
Transcript written on forsydeatom14.log.
* installing tikzlibraryforsyde.pictures.layered.code.tex
* installing tikzlibraryforsyde.utils.code.tex
* installing tikzlibraryforsyde.paths.code.tex
* installing tikzlibraryforsyde.shapes.code.tex
* installing tikzlibraryforsyde.keys.code.tex
* installing tikzlibraryforsyde.nodes.code.tex
* installing forsyde.sty
* installing forsyde-math.sty
* installing forsyde-legacy.sty
* installing forsyde-tikz.sty
* installing ezkeys.sty
* installing forsyde-plot.sty
Package ForSyDe-LaTex installed in /home/edil/texmf
```

Make on the paper repository fails with:
```
ABD: EveryShipout initializing macros
Package pgfplots notification 'compat/show suggested version=true': you might b
enefit from \pgfplotsset{compat=1.14} (current compat level: 1.13).


! Package pgfkeys Error: I do not know the key '/ctsignalkeys/step', to which y
ou passed '.2', and I am going to ignore it. Perhaps you misspelled it.

See the pgfkeys package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.8 ...  \signalCT[outline,ordinate=0,step=.2]{-1}
                                                  {1}{0.0,0.1980198019801980...

? 
```

The error stays even with `texhash /home/edil/texmf`.

**Comment by joseedil** [comment] 2018-03-14 21:39
2. Sudo:
```
$> sudo make install
* installing forsydeatom.mf
* installing forsydeatom10.mf
* installing forsydeatom8.mf
* installing forsydeatom14.mf
* generating fontmap for forsydeatom8.tfm
This is METAFONT, Version 2.7182818 (TeX Live 2016/Debian) (preloaded base=mf)

(fonts/forsydeatom8.mf
kpathsea: Running mktexmf forsydeatom

! I can't find file `forsydeatom'.
l.7 input forsydeatom
                     
Please type another input file name
! Emergency stop.
l.7 input forsydeatom
                     
Transcript written on forsydeatom8.log.
rm: não foi possível remover '*gf': Arquivo ou diretório não encontrado
Makefile:71: recipe for target '/usr/local/share/texmf/fonts/tfm/foundry/typeface/forsydeatom8.tfm' failed
make: *** [/usr/local/share/texmf/fonts/tfm/foundry/typeface/forsydeatom8.tfm] Error 1
```

And I cannot find the log anywhere...

**Comment by joseedil** [comment] 2018-03-14 21:43
Ok, now the 'issue-10' branch version.

```
$> make install
* installing forsydeatom.mf
* installing forsydeatom10.mf
* installing forsydeatom8.mf
* installing forsydeatom14.mf
* generating fontmap for forsydeatom8.tfm
This is METAFONT, Version 2.7182818 (TeX Live 2016/Debian) (preloaded base=mf)

(fonts/forsydeatom8.mf
(/home/edil/texmf/fonts/source/public/typeface/forsydeatom.mf [16] [17]
[18] [19] [20] [32] [33] [34] [35] [36] [37] [48] [49] [50] [51] [52] [53] ) )
Font metrics written on forsydeatom8.tfm.
Output written on forsydeatom8.600gf (17 characters, 5824 bytes).
Transcript written on forsydeatom8.log.
* generating fontmap for forsydeatom10.tfm
This is METAFONT, Version 2.7182818 (TeX Live 2016/Debian) (preloaded base=mf)

(fonts/forsydeatom10.mf
(/home/edil/texmf/fonts/source/public/typeface/forsydeatom.mf [16] [17]
[18] [19] [20] [32] [33] [34] [35] [36] [37] [48] [49] [50] [51] [52] [53] ) )
Font metrics written on forsydeatom10.tfm.
Output written on forsydeatom10.600gf (17 characters, 6592 bytes).
Transcript written on forsydeatom10.log.
* generating fontmap for forsydeatom14.tfm
This is METAFONT, Version 2.7182818 (TeX Live 2016/Debian) (preloaded base=mf)

(fonts/forsydeatom14.mf
(/home/edil/texmf/fonts/source/public/typeface/forsydeatom.mf [16] [17]
[18] [19] [20] [32] [33] [34] [35] [36] [37] [48] [49] [50] [51] [52] [53] ) )
Font metrics written on forsydeatom14.tfm.
Output written on forsydeatom14.600gf (17 characters, 8412 bytes).
Transcript written on forsydeatom14.log.
* installing tikzlibraryforsyde.pictures.layered.code.tex
* installing tikzlibraryforsyde.utils.code.tex
* installing tikzlibraryforsyde.paths.code.tex
* installing tikzlibraryforsyde.shapes.code.tex
* installing tikzlibraryforsyde.keys.code.tex
* installing tikzlibraryforsyde.nodes.code.tex
* installing forsyde.sty
* installing forsyde-math.sty
* installing forsyde-legacy.sty
* installing forsyde-tikz.sty
* installing ezkeys.sty
* installing forsyde-plot.sty
texhash: /usr/local/share/texmf: directory not writable. Skipping...
texhash: /var/lib/texmf: directory not writable. Skipping...
texhash: /var/lib/texmf: directory not writable. Skipping...
texhash: /var/lib/texmf: directory not writable. Skipping...
texhash: Done.
Package ForSyDe-LaTex installed in /home/edil/texmf
```

Make on the paper still won't compile:
```
ABD: EveryShipout initializing macros
Package pgfplots notification 'compat/show suggested version=true': you might b
enefit from \pgfplotsset{compat=1.14} (current compat level: 1.13).


! Package pgfkeys Error: I do not know the key '/ctsignalkeys/step', to which y
ou passed '.2', and I am going to ignore it. Perhaps you misspelled it.

See the pgfkeys package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.8 ...  \signalCT[outline,ordinate=0,step=.2]{-1}
                                                  {1}{0.0,0.1980198019801980...

? 
```

And `texhash /home/edil/texmf` does not solve the problem.

**Comment by joseedil** [comment] 2018-03-14 21:45
Sudo try:

```
$> sudo make install
* installing forsydeatom.mf
* installing forsydeatom10.mf
* installing forsydeatom8.mf
* installing forsydeatom14.mf
* generating fontmap for forsydeatom8.tfm
This is METAFONT, Version 2.7182818 (TeX Live 2016/Debian) (preloaded base=mf)

(fonts/forsydeatom8.mf
kpathsea: Running mktexmf forsydeatom

! I can't find file `forsydeatom'.
l.7 input forsydeatom
                     
Please type another input file name
! Emergency stop.
l.7 input forsydeatom
                     
Transcript written on forsydeatom8.log.
rm: não foi possível remover '*gf': Arquivo ou diretório não encontrado
Makefile:98: recipe for target '/usr/local/share/texmf/fonts/tfm/foundry/typeface/forsydeatom8.tfm' failed
make: *** [/usr/local/share/texmf/fonts/tfm/foundry/typeface/forsydeatom8.tfm] Error 1
```

**Comment by joseedil** [comment] 2018-03-14 21:59
Reverting to the previous commit does not solve the problem... 

@ugeorge, could you help?

**Comment by joseedil** [comment] 2018-03-14 22:41
I manually set the TEXMFLOCAL and TEXMFHOME variables and installed to TEXMFHOME.

It is now able to compile the manual...

**Comment by joseedil** [comment] 2018-03-14 22:51
And it is clearly looking at my home folder for the files during the paper compilation:

```
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryarrows.code.
tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarythrough.code.tex)
(/home/edil/.texmf/tex/latex/forsyde/tikzlibraryforsyde.shapes.code.tex)
(/home/edil/.texmf/tex/latex/forsyde/tikzlibraryforsyde.paths.code.tex
(/home/edil/.texmf/tex/latex/forsyde/tikzlibraryforsyde.utils.code.tex))
(/home/edil/.texmf/tex/latex/forsyde/tikzlibraryforsyde.nodes.code.tex))
(/home/edil/.texmf/tex/latex/forsyde/forsyde-math.sty
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
```

**Comment by ugeorge** [comment] 2018-03-14 23:45
Your home folder will always have higher priority than local. As per [this thread](https://tex.stackexchange.com/a/73017):

> One thing to note here is that in the case of a 'package clash', i.e., the same file is found in multiple places (such as the 'system' location, the 'local' location, and/or the 'individual user' location), only the first instance of the file will be used. In this case, the order of precedence is usually: individual user (TEXMFHOME) > local (TEXMFLOCAL) > system. The full list (in the right order) can be determined by running kpsewhich --var-value TEXINPUTS.

For the compilation errors you posted, it seems that you were using some old files which still had an experimental (and faulty) signal plot syntax. The package has since evolved, but not the files. I have seen to it that they are upgraded. The benchmark should be the user manual, and (in the future) files after `forsyde-latex-0.2.0`. 

For the `sudo make install` fault, can you send me the log? (i.e. `Transcript written on forsydeatom8.log.`) Also, extremely helpful would be if you can alter the `Makefile` in the following way:

1. type in `sudo make uninstall`
1. remove lines [58-59](https://github.com/forsyde/forsyde-latex/blob/029786cdd4702c190c2146fffaaeecbdff9e5179/Makefile#L58)
1. replace in line [98](https://github.com/forsyde/forsyde-latex/blob/029786cdd4702c190c2146fffaaeecbdff9e5179/Makefile#L98) the word `eval` with the word `info`
1. type in `sudo make install`

Instead of installing by evaluating the rules, it should print them out as they are expanded. That might shed some light on what is happening on your machine.

**Comment by joseedil** [comment] 2018-03-15 16:54
Still can't tell what is wrong here because on my Debian box at UnB, it just worked with `sudo make install` but on my personal box running the same Debian setup on a VM it won't...

**Comment by joseedil** [comment] 2018-03-15 16:54
By the way, the log here is never generated...

**Comment by joseedil** [comment] 2018-03-15 16:58
My bad, at UnB it won't work with the sudo version. It installs the files to the right place but LaTeX can't find them when compiling the manual.

My suggestion is to remove the sudo version from the README and suggest only the home install that seems to be all right.

**Comment by ugeorge** [comment] 2018-03-15 21:24
Even after the added `texhash`? Strange... I guess taking out the sudo version from the instructions seems the most straightforward solution. And maybe mention it as a side note, to be used with care. Since on all the machines at KTH the installation did not complain, I cannot reproduce the bug, so I will have to close the issue. Later, when the library becomes more stable I will see to it how to distribute the package on CTAN.

**Closed as completed** 2018-03-15 21:25 UTC
Labels: invalid
